// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notepad.EntityFramework.EntityFrameworkCore.Contexts;

namespace Notepad.EntityFramework.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20210728001551_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Notepad.Domain.Cities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b49ad5-3b32-446c-f944-08d9515cdba8"),
                            CityName = "Adana",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(1366),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(1808)
                        },
                        new
                        {
                            Id = new Guid("f50cb2b5-8a29-492c-f945-08d9515cdba8"),
                            CityName = "Adıyaman",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2225),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2227)
                        },
                        new
                        {
                            Id = new Guid("9e26f48a-e0ce-4b8a-f946-08d9515cdba8"),
                            CityName = "Afyonkarahisar",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2234),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2235)
                        },
                        new
                        {
                            Id = new Guid("4e7855a5-a482-4a0f-f947-08d9515cdba8"),
                            CityName = "Ağrı",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2242),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2244)
                        },
                        new
                        {
                            Id = new Guid("23df673e-4fb2-4bdd-f948-08d9515cdba8"),
                            CityName = "Amasya",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2250),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2252)
                        },
                        new
                        {
                            Id = new Guid("bb10baa5-694c-4e0a-f949-08d9515cdba8"),
                            CityName = "Ankara",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2273),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2274)
                        },
                        new
                        {
                            Id = new Guid("b517156b-865e-41b1-f94a-08d9515cdba8"),
                            CityName = "Antalya",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2281),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2282)
                        },
                        new
                        {
                            Id = new Guid("3df3f4d2-9441-4c9c-f94b-08d9515cdba8"),
                            CityName = "Artvin",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2289),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2290)
                        },
                        new
                        {
                            Id = new Guid("d521a13f-a7c7-4ffa-f94c-08d9515cdba8"),
                            CityName = "Aydın",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2297),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2298)
                        },
                        new
                        {
                            Id = new Guid("8ad04a1d-64bc-4d08-f94d-08d9515cdba8"),
                            CityName = "Balıkesir",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2305),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2306)
                        },
                        new
                        {
                            Id = new Guid("5fd7f4cd-a0e3-4ed0-f94e-08d9515cdba8"),
                            CityName = "Bilecik",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2313),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2314)
                        },
                        new
                        {
                            Id = new Guid("d49cc89e-244d-4c4f-f94f-08d9515cdba8"),
                            CityName = "Bingöl",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2320),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2322)
                        },
                        new
                        {
                            Id = new Guid("d021e79b-340d-4fcf-f950-08d9515cdba8"),
                            CityName = "Bitlis",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2328),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2330)
                        },
                        new
                        {
                            Id = new Guid("734ad1f7-850f-49be-f951-08d9515cdba8"),
                            CityName = "Bolu",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2340),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2342)
                        },
                        new
                        {
                            Id = new Guid("96b5d9af-6a7c-4c23-f952-08d9515cdba8"),
                            CityName = "Burdur",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2348),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2349)
                        },
                        new
                        {
                            Id = new Guid("3532f809-4126-4d12-f953-08d9515cdba8"),
                            CityName = "Bursa",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2356),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2357)
                        },
                        new
                        {
                            Id = new Guid("94d30b6f-a008-448c-f954-08d9515cdba8"),
                            CityName = "Çanakkale",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2364),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2365)
                        },
                        new
                        {
                            Id = new Guid("2d5b1447-88ec-4b99-f955-08d9515cdba8"),
                            CityName = "Çankırı",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2372),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2373)
                        },
                        new
                        {
                            Id = new Guid("cc313a37-22e5-4eec-f956-08d9515cdba8"),
                            CityName = "Çorum",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2380),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2381)
                        },
                        new
                        {
                            Id = new Guid("8755be4c-0c57-4955-f957-08d9515cdba8"),
                            CityName = "Denizli",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2388),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2389)
                        },
                        new
                        {
                            Id = new Guid("40392801-a9c7-4ec7-f958-08d9515cdba8"),
                            CityName = "Diyarbakır",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2395),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2397)
                        },
                        new
                        {
                            Id = new Guid("e7fb068a-1972-4b05-f959-08d9515cdba8"),
                            CityName = "Edirne",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2406),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2408)
                        },
                        new
                        {
                            Id = new Guid("1651b938-d072-4047-f95a-08d9515cdba8"),
                            CityName = "Elazığ",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2414),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2416)
                        },
                        new
                        {
                            Id = new Guid("244c175d-dbee-465f-f95b-08d9515cdba8"),
                            CityName = "Erzincan",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2422),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2423)
                        },
                        new
                        {
                            Id = new Guid("a09114da-3bcb-4ddd-f95c-08d9515cdba8"),
                            CityName = "Erzurum",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2430),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2431)
                        },
                        new
                        {
                            Id = new Guid("aca7065a-9f70-4448-f95d-08d9515cdba8"),
                            CityName = "Eskişehir",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2438),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2439)
                        },
                        new
                        {
                            Id = new Guid("458af0af-55b8-4d1b-f95e-08d9515cdba8"),
                            CityName = "Gaziantep",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2446),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2447)
                        },
                        new
                        {
                            Id = new Guid("4b2d3a3a-9224-46cb-f95f-08d9515cdba8"),
                            CityName = "Giresun",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2453),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2455)
                        },
                        new
                        {
                            Id = new Guid("439d7c7c-21fd-4687-f960-08d9515cdba8"),
                            CityName = "Gümüşhane",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2461),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2463)
                        },
                        new
                        {
                            Id = new Guid("4eb784d0-9511-48bd-f961-08d9515cdba8"),
                            CityName = "Hakkâri",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2472),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2473)
                        },
                        new
                        {
                            Id = new Guid("ae7a60a3-dff8-413c-f962-08d9515cdba8"),
                            CityName = "Hatay",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2479),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2481)
                        },
                        new
                        {
                            Id = new Guid("5db18fb7-807d-4311-f963-08d9515cdba8"),
                            CityName = "Isparta",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2550),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2551)
                        },
                        new
                        {
                            Id = new Guid("063ab0df-df7a-448c-f964-08d9515cdba8"),
                            CityName = "Mersin",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2558),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2559)
                        },
                        new
                        {
                            Id = new Guid("7ea3e759-aace-4f42-f965-08d9515cdba8"),
                            CityName = "İstanbul",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2566),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2567)
                        },
                        new
                        {
                            Id = new Guid("78a10d31-2304-4cdd-f966-08d9515cdba8"),
                            CityName = "İzmir",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2574),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2575)
                        },
                        new
                        {
                            Id = new Guid("b40eae40-f1af-4c3b-f967-08d9515cdba8"),
                            CityName = "Kars",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2581),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2583)
                        },
                        new
                        {
                            Id = new Guid("19c3d41b-1650-48b1-f968-08d9515cdba8"),
                            CityName = "Kastamonu",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2589),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2591)
                        },
                        new
                        {
                            Id = new Guid("ccc1a0e8-6a91-482b-f969-08d9515cdba8"),
                            CityName = "Kayseri",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2600),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2601)
                        },
                        new
                        {
                            Id = new Guid("a50a90d9-7046-4aed-f96a-08d9515cdba8"),
                            CityName = "Kırklareli",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2608),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2609)
                        },
                        new
                        {
                            Id = new Guid("ddf908de-af0c-48db-f96b-08d9515cdba8"),
                            CityName = "Kırşehir",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2615),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2617)
                        },
                        new
                        {
                            Id = new Guid("1e6eb2d7-80e6-4e72-f96c-08d9515cdba8"),
                            CityName = "Kocaeli",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2623),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2625)
                        },
                        new
                        {
                            Id = new Guid("675cd6b7-b164-468a-f96d-08d9515cdba8"),
                            CityName = "Konya",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2631),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2633)
                        },
                        new
                        {
                            Id = new Guid("c33269cb-9b71-4da3-f96e-08d9515cdba8"),
                            CityName = "Kütahya",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2639),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2640)
                        },
                        new
                        {
                            Id = new Guid("0c931e4d-e62b-474b-f96f-08d9515cdba8"),
                            CityName = "Malatya",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2647),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2648)
                        },
                        new
                        {
                            Id = new Guid("1cfdb070-4c5b-4b26-f970-08d9515cdba8"),
                            CityName = "Manisa",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2654),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2656)
                        },
                        new
                        {
                            Id = new Guid("d6de0983-5bd5-495e-f971-08d9515cdba8"),
                            CityName = "Kahramanmaraş",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2665),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2666)
                        },
                        new
                        {
                            Id = new Guid("da4fdfe6-1ac2-4eb9-f972-08d9515cdba8"),
                            CityName = "Mardin",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2672),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2674)
                        },
                        new
                        {
                            Id = new Guid("0845808e-05eb-462c-f973-08d9515cdba8"),
                            CityName = "Muğla",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2680),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2681)
                        },
                        new
                        {
                            Id = new Guid("82ac6c08-5c45-4f6d-f974-08d9515cdba8"),
                            CityName = "Muş",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2688),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2689)
                        },
                        new
                        {
                            Id = new Guid("cc8e7bea-dd8d-4e28-f975-08d9515cdba8"),
                            CityName = "Nevşehir",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2695),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2697)
                        },
                        new
                        {
                            Id = new Guid("5a16bd4a-e9b5-4e29-f976-08d9515cdba8"),
                            CityName = "Niğde",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2703),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2705)
                        },
                        new
                        {
                            Id = new Guid("14900165-54e5-40e7-f977-08d9515cdba8"),
                            CityName = "Ordu",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2711),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2712)
                        },
                        new
                        {
                            Id = new Guid("1560e5ca-a97f-449e-f978-08d9515cdba8"),
                            CityName = "Rize",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2718),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2720)
                        },
                        new
                        {
                            Id = new Guid("9ce0899f-aaf2-413d-f979-08d9515cdba8"),
                            CityName = "Sakarya",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2729),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2730)
                        },
                        new
                        {
                            Id = new Guid("904b279b-27c4-493d-f97a-08d9515cdba8"),
                            CityName = "Samsun",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2736),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2738)
                        },
                        new
                        {
                            Id = new Guid("20597945-cd86-484f-f97b-08d9515cdba8"),
                            CityName = "Siirt",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2744),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2746)
                        },
                        new
                        {
                            Id = new Guid("ea1a270c-e417-480a-f97c-08d9515cdba8"),
                            CityName = "Sinop",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2752),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2754)
                        },
                        new
                        {
                            Id = new Guid("077a50e6-65c4-47a7-f97d-08d9515cdba8"),
                            CityName = "Sivas",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2760),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2761)
                        },
                        new
                        {
                            Id = new Guid("c87f0634-246c-4d0c-f97e-08d9515cdba8"),
                            CityName = "Tekirdağ",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2768),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2769)
                        },
                        new
                        {
                            Id = new Guid("91c5e61b-51fb-4627-f97f-08d9515cdba8"),
                            CityName = "Tokat",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2775),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2777)
                        },
                        new
                        {
                            Id = new Guid("6412faab-2685-498e-f980-08d9515cdba8"),
                            CityName = "Trabzon",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2783),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2785)
                        },
                        new
                        {
                            Id = new Guid("f77c8d7d-d635-4cf2-f981-08d9515cdba8"),
                            CityName = "Tunceli",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2793),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2795)
                        },
                        new
                        {
                            Id = new Guid("9f477796-3874-4062-f982-08d9515cdba8"),
                            CityName = "Şanlıurfa",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2801),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2803)
                        },
                        new
                        {
                            Id = new Guid("10b20af8-7f89-4f1d-f983-08d9515cdba8"),
                            CityName = "Uşak",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2809),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2810)
                        },
                        new
                        {
                            Id = new Guid("bbcfb717-718c-4903-f984-08d9515cdba8"),
                            CityName = "Van",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2817),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2818)
                        },
                        new
                        {
                            Id = new Guid("32e31a36-1fa3-45c7-f985-08d9515cdba8"),
                            CityName = "Yozgat",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2824),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2826)
                        },
                        new
                        {
                            Id = new Guid("7f489aec-38b9-429f-f986-08d9515cdba8"),
                            CityName = "Zonguldak",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2832),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2833)
                        },
                        new
                        {
                            Id = new Guid("40b2a17a-3182-4166-f987-08d9515cdba8"),
                            CityName = "Aksaray",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2840),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2841)
                        },
                        new
                        {
                            Id = new Guid("3652a9d0-f22f-429c-f988-08d9515cdba8"),
                            CityName = "Bayburt",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2848),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2850)
                        },
                        new
                        {
                            Id = new Guid("9348ee7c-a1eb-46c7-f989-08d9515cdba8"),
                            CityName = "Karaman",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2858),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2860)
                        },
                        new
                        {
                            Id = new Guid("51c29efc-3e9d-4aa5-f98a-08d9515cdba8"),
                            CityName = "Kırıkkale",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2866),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2868)
                        },
                        new
                        {
                            Id = new Guid("e83a411c-4e7e-4e8a-f98b-08d9515cdba8"),
                            CityName = "Batman",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2874),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2875)
                        },
                        new
                        {
                            Id = new Guid("bed6c450-f8f1-457f-f98c-08d9515cdba8"),
                            CityName = "Şırnak",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2881),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2883)
                        },
                        new
                        {
                            Id = new Guid("95a89454-6063-4714-f98d-08d9515cdba8"),
                            CityName = "Bartın",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2889),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2890)
                        },
                        new
                        {
                            Id = new Guid("e0296fac-6fbc-4f18-f98e-08d9515cdba8"),
                            CityName = "Ardahan",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2897),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2898)
                        },
                        new
                        {
                            Id = new Guid("bb4b5db1-bd9b-4c58-f98f-08d9515cdba8"),
                            CityName = "Iğdır",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2904),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2906)
                        },
                        new
                        {
                            Id = new Guid("0fce1634-8107-4408-f990-08d9515cdba8"),
                            CityName = "Yalova",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2912),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2914)
                        },
                        new
                        {
                            Id = new Guid("90ea19b7-18bf-416b-f991-08d9515cdba8"),
                            CityName = "Karabük",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2991),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(2992)
                        },
                        new
                        {
                            Id = new Guid("cdaf4567-b0c5-4321-f992-08d9515cdba8"),
                            CityName = "Kilis",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(3000),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(3001)
                        },
                        new
                        {
                            Id = new Guid("ccf55da5-5bff-484d-f993-08d9515cdba8"),
                            CityName = "Osmaniye",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(3007),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(3009)
                        },
                        new
                        {
                            Id = new Guid("c74c051f-4e8d-4cba-f994-08d9515cdba8"),
                            CityName = "Düzce",
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(3015),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 377, DateTimeKind.Local).AddTicks(3016)
                        });
                });

            modelBuilder.Entity("Notepad.Domain.NoteCategories.NoteCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteCategoryDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoteCategoryTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("NoteCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c237e6fb-1404-4d1a-f995-08d9515cdba8"),
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 379, DateTimeKind.Local).AddTicks(5027),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 379, DateTimeKind.Local).AddTicks(5033),
                            NoteCategoryDescription = "Önemli Notlar",
                            NoteCategoryTitle = "Önemli"
                        },
                        new
                        {
                            Id = new Guid("610f6af5-df4d-4ac3-f996-08d9515cdba8"),
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 379, DateTimeKind.Local).AddTicks(5767),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 379, DateTimeKind.Local).AddTicks(5771),
                            NoteCategoryDescription = "Yazılımla Alakalı Notlar",
                            NoteCategoryTitle = "Yazılım"
                        },
                        new
                        {
                            Id = new Guid("8c95f375-6beb-463d-f997-08d9515cdba8"),
                            CreatedDate = new DateTime(2021, 7, 28, 3, 15, 51, 379, DateTimeKind.Local).AddTicks(5775),
                            ModifiedDate = new DateTime(2021, 7, 28, 3, 15, 51, 379, DateTimeKind.Local).AddTicks(5776),
                            NoteCategoryDescription = "İş İle İlgili Notlar",
                            NoteCategoryTitle = "İş"
                        });
                });

            modelBuilder.Entity("Notepad.Domain.Notes.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Notepad.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("LoginHit")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Notepad.Domain.Notes.Note", b =>
                {
                    b.HasOne("Notepad.Domain.NoteCategories.NoteCategory", "Category")
                        .WithMany("NoteRelation")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notepad.Domain.Users.User", "User")
                        .WithMany("NoteRelation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Notepad.Domain.Users.User", b =>
                {
                    b.HasOne("Notepad.Domain.Cities.City", "City")
                        .WithMany("UserRelation")
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Notepad.Domain.Cities.City", b =>
                {
                    b.Navigation("UserRelation");
                });

            modelBuilder.Entity("Notepad.Domain.NoteCategories.NoteCategory", b =>
                {
                    b.Navigation("NoteRelation");
                });

            modelBuilder.Entity("Notepad.Domain.Users.User", b =>
                {
                    b.Navigation("NoteRelation");
                });
#pragma warning restore 612, 618
        }
    }
}
